### ISSUE TITLE
Adding interface for Hiera and nrpe resources

### ISSUE THREAD

**Issue by jehane** [voxpupuli/puppet-nrpe#16]
It would be useful to add nrpre ressources through hiera. 
A pull request exist for pdcat/puppet-module-nrpe  ( 
https://github.com/pdxcat/puppet-module-nrpe/pull/42 )

Is it possible to add this feature ? 

Thanks

**Comment by alexjfisher** [comment]
@jehane Seems reasonable, so I created https://github.com/voxpupuli/puppet-nrpe/pull/17.

Does that work for you?

(https://github.com/pdxcat/puppet-module-nrpe/pull/42 has some slightly odd implementation for plugins.  I think the idea was you might want to be able to pass a template in for plugins.  In practice, I'm not sure how well that would work.  Would the variables you want to use in your template be in scope when created by the `nrpe` class?  Not sure.  Either way, I think I'd implement this by adding a `template` parameter to the `nrpe::plugin` class.)

**Comment by jehane** [comment]
It looks great for me. 
Thanks !

**Comment by jehane** [comment]
Our goal is to be able to, first modify some default check (modifying arguments) and add new one in nrpe configuration, second, deploy scripts for custom checks (not available through deb or rpm)

**Comment by jehane** [comment]
It look great. 

We want to add/modify commands in nrpe config files (changing parameters for checks, adding some new one, etc). 
And on a second time, deploy scripts for specific checks (who are not available through deb or rpm). 

And do all of it through hiera, of course

Thansk again
