### ISSUE TITLE
nrpe Package on 20.04 is Persistently Reinstalling as a Corrective Action

### ISSUE THREAD

**Issue by jamboNum5** [voxpupuli/puppet-nrpe#65]
Puppet: 6 / Distribution: Centos 7 (Puppet Master) / Module version: 5.0.0 / Foreman 3.2.0

The problem occures when machines check in with puppet. All hosts running Ubuntu 20.04 are checking in and persistently get nrpe reinstalled with the following message.

`Notice: /Stage[main]/Nrpe::Install/Package[nagios-plugins]/ensure: created (corrective)`

Curiously, this doesn't seem to happen on 18.04 machines. I can see the .deb packages share the same name on each system.

I expected the module to detect that it has already been installed, much like it doesn't on 18.04. This isn't a crucial bug, but it does clog up the dashboard report a little when I'm trying to see what changes have been pushed out, I'm keen to minimise actions that aren't needed.

I did take a quick look in the npre module, I'm not sure I understand the method used to install nrpe as it is a bit beyond my puppet skills. But if you have a suggestion on how to troubleshoot this, I'm be more than happy to give something a go.

**Comment by jmcdonal** [comment]
I'm having the same problem with debian version 11 x86_64.   The problem seems to be that nagios-plugins have been renamed by the package managers as monitoring-plugins.

**Comment by jamboNum5** [comment]
I think this might be because there isn't strictly a package named nagios-plugins on 20.04, given that I'm no longer using 18.04, can replace nagios-plugins with nagios-plugins-contrib from the install.pp under the Debian section.

```
apt-cache search nagios-plugins
monitoring-plugins - Plugins for nagios compatible monitoring systems (metapackage)
monitoring-plugins-basic - Plugins for nagios compatible monitoring systems (basic)
monitoring-plugins-standard - Plugins for nagios compatible monitoring systems (standard)
nagios-plugins-contrib - Plugins for nagios compatible monitoring systems
nagios-plugins-rabbitmq - Set of Nagios checks useful for monitoring a RabbitMQ server
nordugrid-arc-nagios-plugins - Nagios plugins for ARC
nordugrid-arc-nagios-plugins-doc - HTML documentation for the ARC Nagios plugins
nordugrid-arc-nagios-plugins-egi - EGI configuration and dependencies for the ARC Nagios plugins
```
